import os
import io
import datetime
from typing import Dict, Any, Optional

import matplotlib
matplotlib.use("Agg") # Non-interactive backend
import matplotlib.pyplot as plt

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "Smart Multi-Agent AI Code Reviewer v2.0 - Automated Review Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 744, 558, 744)

        # Footer (all pages)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_text)
        self.drawString(54, 36, "Confidential - Generated by Smart Multi-Agent AI Review System")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        self.restoreState()

class PDFReportService:
    @staticmethod
    def _create_agent_chart(scores: Dict[str, int]) -> bytes:
        plt.figure(figsize=(6.5, 2.8), dpi=200)
        agents = ["Security", "Quality", "Performance", "Testing", "Maintainability"]
        vals = [
            scores.get("security", 0),
            scores.get("code_quality", 0),
            scores.get("performance", 0),
            scores.get("testing", 0),
            scores.get("maintainability", 0)
        ]
        bar_colors = ["#10B981" if v >= 80 else "#F59E0B" if v >= 60 else "#EF4444" for v in vals]
        
        bars = plt.bar(agents, vals, color=bar_colors, width=0.55, edgecolor="#0F172A", linewidth=0.8)
        plt.title("Agent Performance Scores (0 - 100)", fontsize=11, fontweight="bold", pad=10, color="#1E293B")
        plt.ylim(0, 110)
        plt.grid(axis="y", linestyle="--", alpha=0.4)
        plt.gca().set_axisbelow(True)
        
        for bar in bars:
            h = bar.get_height()
            plt.text(bar.get_x() + bar.get_width()/2., h + 2, f"{int(h)}%", ha="center", va="bottom", fontsize=9, fontweight="bold", color="#1E293B")

        plt.tight_layout()
        buf = io.BytesIO()
        plt.savefig(buf, format="png", bbox_inches="tight")
        plt.close()
        buf.seek(0)
        return buf.getvalue()

    @staticmethod
    def _create_risk_chart(pred: Dict[str, Any]) -> bytes:
        plt.figure(figsize=(6.5, 2.8), dpi=200)
        categories = ["Bug Risk", "Security Risk", "Regression Risk", "Tech Debt", "Overall Risk"]
        vals = [
            pred.get("bug_risk", 0),
            pred.get("security_risk", 0),
            pred.get("regression_risk", 0),
            pred.get("technical_debt", 0),
            pred.get("overall_risk", 0)
        ]
        bar_colors = ["#EF4444" if v > 50 else "#F59E0B" if v > 20 else "#10B981" for v in vals]

        bars = plt.bar(categories, vals, color=bar_colors, width=0.55, edgecolor="#0F172A", linewidth=0.8)
        plt.title("Risk Breakdown & Predictive Analysis (%)", fontsize=11, fontweight="bold", pad=10, color="#1E293B")
        plt.ylim(0, 110)
        plt.grid(axis="y", linestyle="--", alpha=0.4)
        plt.gca().set_axisbelow(True)

        for bar in bars:
            h = bar.get_height()
            plt.text(bar.get_x() + bar.get_width()/2., h + 2, f"{int(h)}%", ha="center", va="bottom", fontsize=9, fontweight="bold", color="#1E293B")

        plt.tight_layout()
        buf = io.BytesIO()
        plt.savefig(buf, format="png", bbox_inches="tight")
        plt.close()
        buf.seek(0)
        return buf.getvalue()

    @staticmethod
    def _create_consensus_chart(local_score: int, groq_score: Optional[int]) -> bytes:
        plt.figure(figsize=(5.0, 2.6), dpi=200)
        labels = ["Local Multi-Agent", "External Groq AI"]
        vals = [local_score, groq_score if groq_score is not None else 0]
        colors_list = ["#3B82F6", "#8B5CF6"]

        bars = plt.bar(labels, vals, color=colors_list, width=0.45, edgecolor="#0F172A", linewidth=0.8)
        plt.title("Local Multi-Agent vs. External Groq AI Score", fontsize=10, fontweight="bold", pad=10, color="#1E293B")
        plt.ylim(0, 110)
        plt.grid(axis="y", linestyle="--", alpha=0.4)
        plt.gca().set_axisbelow(True)

        for bar in bars:
            h = bar.get_height()
            if h > 0:
                plt.text(bar.get_x() + bar.get_width()/2., h + 2, f"{int(h)}/100", ha="center", va="bottom", fontsize=9, fontweight="bold", color="#1E293B")
            else:
                plt.text(bar.get_x() + bar.get_width()/2., 10, "N/A", ha="center", va="bottom", fontsize=9, fontweight="bold", color="#64748B")

        plt.tight_layout()
        buf = io.BytesIO()
        plt.savefig(buf, format="png", bbox_inches="tight")
        plt.close()
        buf.seek(0)
        return buf.getvalue()

    @classmethod
    def generate_pdf_report(cls, review_data: Dict[str, Any], output_path: str) -> str:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0F172A")
        )
        subtitle_style = ParagraphStyle(
            "DocSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=11,
            leading=15,
            textColor=colors.HexColor("#64748B")
        )
        h2_style = ParagraphStyle(
            "Heading2Custom",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=colors.HexColor("#1E293B"),
            spaceBefore=14,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            "BodyCustom",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155")
        )
        code_style = ParagraphStyle(
            "CodeCustom",
            parent=styles["Normal"],
            fontName="Courier",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#0F172A")
        )

        story = []

        # 1. Header & Title Block
        story.append(Paragraph("SMART MULTI-AGENT AI CODE REVIEWER", title_style))
        story.append(Paragraph("Automated Multi-Agent Static, Predictive & Consensus Analysis Report", subtitle_style))
        story.append(Spacer(1, 10))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#3B82F6"), spaceAfter=12))

        # Metadata Table
        review_id = review_data.get("review_id", "N/A")
        user_id = review_data.get("user_id", "N/A")
        created_at = review_data.get("created_at", datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"))
        target_name = review_data.get("target_name", "snippet")
        language = review_data.get("primary_language", "Generic")

        meta_data = [
            [
                Paragraph(f"<b>Review ID:</b> {review_id}", body_style),
                Paragraph(f"<b>User ID:</b> {user_id}", body_style)
            ],
            [
                Paragraph(f"<b>Target:</b> {target_name} ({language})", body_style),
                Paragraph(f"<b>Date:</b> {created_at}", body_style)
            ]
        ]
        meta_table = Table(meta_data, colWidths=[250, 250])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 14))

        # 2. Executive Summary / Score Cards
        scores = review_data.get("scores", {})
        pred = review_data.get("predictions", {})
        overall_score = scores.get("overall", 0)
        risk_score = pred.get("overall_risk", 0)
        risk_level = pred.get("risk_level", "LOW")
        bug_prob = pred.get("future_bug_probability", 0)

        risk_color = "#10B981" if risk_level == "LOW" else "#F59E0B" if risk_level == "MEDIUM" else "#EF4444"

        cards_data = [
            [
                Paragraph(f"<font size=8 color='#64748B'>OVERALL SCORE</font><br/><font size=18 color='#0F172A'><b>{overall_score}/100</b></font>", body_style),
                Paragraph(f"<font size=8 color='#64748B'>RISK LEVEL</font><br/><font size=18 color='{risk_color}'><b>{risk_level}</b></font>", body_style),
                Paragraph(f"<font size=8 color='#64748B'>OVERALL RISK</font><br/><font size=18 color='{risk_color}'><b>{risk_score}%</b></font>", body_style),
                Paragraph(f"<font size=8 color='#64748B'>FUTURE BUG PROB.</font><br/><font size=18 color='#0F172A'><b>{bug_prob}%</b></font>", body_style),
            ]
        ]
        cards_table = Table(cards_data, colWidths=[125, 125, 125, 125])
        cards_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(cards_table)
        story.append(Spacer(1, 14))

        # 3. Agent Performance Graph & Score Table
        story.append(Paragraph("1. Multi-Agent Performance Analysis", h2_style))
        agent_chart_bytes = cls._create_agent_chart(scores)
        story.append(Image(io.BytesIO(agent_chart_bytes), width=480, height=200))
        story.append(Spacer(1, 8))

        agent_table_data = [
            [
                Paragraph("<b>Agent Name</b>", body_style),
                Paragraph("<b>Score</b>", body_style),
                Paragraph("<b>Evaluation Focus</b>", body_style),
                Paragraph("<b>Status</b>", body_style)
            ],
            [
                Paragraph("Security Agent", body_style),
                Paragraph(f"<b>{scores.get('security', 0)}/100</b>", body_style),
                Paragraph("CWEs, Secrets, Injections, Deserialization, Permissions", body_style),
                Paragraph("PASS" if scores.get('security', 0) >= 75 else "WARN", body_style)
            ],
            [
                Paragraph("Code Quality Agent", body_style),
                Paragraph(f"<b>{scores.get('code_quality', 0)}/100</b>", body_style),
                Paragraph("Complexity, Function Length, Smells, Naming, Docstrings", body_style),
                Paragraph("PASS" if scores.get('code_quality', 0) >= 75 else "WARN", body_style)
            ],
            [
                Paragraph("Performance Agent", body_style),
                Paragraph(f"<b>{scores.get('performance', 0)}/100</b>", body_style),
                Paragraph("O(n²) loops, N+1 queries, Resource leaks, Memory", body_style),
                Paragraph("PASS" if scores.get('performance', 0) >= 75 else "WARN", body_style)
            ],
            [
                Paragraph("Testing & Resilience Agent", body_style),
                Paragraph(f"<b>{scores.get('testing', 0)}/100</b>", body_style),
                Paragraph("Error handling, Edge cases, Boundary validation, Test suites", body_style),
                Paragraph("PASS" if scores.get('testing', 0) >= 75 else "WARN", body_style)
            ],
            [
                Paragraph("Prediction Agent", body_style),
                Paragraph(f"<b>{scores.get('maintainability', 0)}/100</b>", body_style),
                Paragraph("Maintainability index & architectural longevity", body_style),
                Paragraph("PASS" if scores.get('maintainability', 0) >= 75 else "WARN", body_style)
            ]
        ]
        agent_table = Table(agent_table_data, colWidths=[120, 60, 260, 60])
        agent_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#94A3B8")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(agent_table)
        story.append(Spacer(1, 14))

        # 4. Risk Analysis Graph
        story.append(Paragraph("2. Risk Analysis & Predictive Model", h2_style))
        risk_chart_bytes = cls._create_risk_chart(pred)
        story.append(Image(io.BytesIO(risk_chart_bytes), width=480, height=200))
        story.append(Spacer(1, 14))

        # 5. Local vs External Groq AI Consensus
        consensus = review_data.get("consensus", {})
        groq_ai = review_data.get("external_ai")
        groq_score = groq_ai.get("overall_score") if groq_ai else None

        story.append(Paragraph("3. Local vs. External Groq AI Consensus Engine", h2_style))
        consensus_chart_bytes = cls._create_consensus_chart(overall_score, groq_score)
        
        comp = consensus.get("comparison", {})
        agreement = comp.get("agreement", "HIGH")
        confidence = consensus.get("confidence", 90)
        explanation = consensus.get("explanation", "High agreement between static analysis and external reviewer.")

        consensus_info = [
            [
                Image(io.BytesIO(consensus_chart_bytes), width=230, height=120),
                [
                    Paragraph(f"<b>Agreement Level:</b> {agreement}", body_style),
                    Spacer(1, 4),
                    Paragraph(f"<b>Confidence Score:</b> {confidence}%", body_style),
                    Spacer(1, 4),
                    Paragraph(f"<b>Score Difference:</b> {comp.get('score_difference', 0)} pts", body_style),
                    Spacer(1, 4),
                    Paragraph(f"<b>Risk Difference:</b> {comp.get('risk_difference', 0)} pts", body_style),
                    Spacer(1, 4),
                    Paragraph(f"<b>Evaluation:</b> {explanation}", body_style)
                ]
            ]
        ]
        consensus_table = Table(consensus_info, colWidths=[240, 260])
        consensus_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(consensus_table)
        story.append(Spacer(1, 14))

        # 6. Detailed Findings Table
        findings = review_data.get("findings", [])
        story.append(Paragraph(f"4. Detailed Inspection Findings ({len(findings)} Total)", h2_style))
        
        if not findings:
            story.append(Paragraph("No critical vulnerabilities, security risks, or structural flaws detected in analyzed files.", body_style))
        else:
            findings_data = [
                [
                    Paragraph("<b>Sev.</b>", body_style),
                    Paragraph("<b>Category</b>", body_style),
                    Paragraph("<b>File:Line</b>", body_style),
                    Paragraph("<b>Description & Fix Recommendation</b>", body_style)
                ]
            ]
            for f in findings[:25]: # Display top 25 findings
                sev = f.get("severity", "LOW")
                sev_color = "#991B1B" if sev == "CRITICAL" else "#DC2626" if sev == "HIGH" else "#D97706" if sev == "MEDIUM" else "#2563EB"
                
                cat = f.get("category", "General")
                loc = f"{f.get('file', 'code')}:{f.get('line', 1)}"
                desc = f"<b>{f.get('title', '')}</b><br/>{f.get('description', '')}<br/><font color='#047857'><b>Remediation:</b> {f.get('recommendation', '')}</font>"

                findings_data.append([
                    Paragraph(f"<font color='{sev_color}'><b>{sev}</b></font>", body_style),
                    Paragraph(cat, body_style),
                    Paragraph(loc, body_style),
                    Paragraph(desc, body_style)
                ])

            find_table = Table(findings_data, colWidths=[55, 75, 90, 280])
            find_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#94A3B8")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(find_table)

        story.append(Spacer(1, 14))

        # 7. Actionable Recommendations
        recs = review_data.get("recommendations", [])
        story.append(Paragraph("5. Strategic Engineering Recommendations", h2_style))
        for idx, r in enumerate(recs[:8], start=1):
            story.append(Paragraph(f"<b>{idx}.</b> {r}", body_style))
            story.append(Spacer(1, 3))
        story.append(Spacer(1, 10))

        # 8. Generated Unit Tests
        gen_tests = review_data.get("generated_tests", [])
        if gen_tests:
            story.append(Paragraph("6. Recommended Automated Unit Tests", h2_style))
            for gt in gen_tests[:2]:
                story.append(Paragraph(f"<b>Target: {gt.get('file')} ({gt.get('language')})</b>", body_style))
                story.append(Spacer(1, 4))
                # Truncate test code to prevent huge page overflow
                code_snippet = gt.get("code", "")[:800]
                test_box = Table([[Paragraph(code_snippet.replace("\n", "<br/>").replace(" ", "&nbsp;"), code_style)]], colWidths=[500])
                test_box.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ]))
                story.append(test_box)
                story.append(Spacer(1, 8))

        # 9. External Groq Review Summary
        if groq_ai:
            story.append(Paragraph("7. External Groq AI Review Executive Summary", h2_style))
            summary_text = groq_ai.get("summary", "External AI review executed successfully.")
            story.append(Paragraph(f"<i>\"{summary_text}\"</i>", body_style))
            story.append(Spacer(1, 10))

        # 10. Conclusion & Certification
        story.append(Paragraph("8. Final Conclusion", h2_style))
        conclusion_text = (
            f"The codebase underwent comprehensive inspection by 5 autonomous static and predictive agents, "
            f"yielding an Overall Score of <b>{overall_score}/100</b> with a <b>{risk_level}</b> risk categorization ({risk_score}% overall risk). "
            f"Addressing the highlighted high-priority security and quality findings will substantially reduce the future defect probability (currently estimated at {bug_prob}%)."
        )
        story.append(Paragraph(conclusion_text, body_style))

        # Build document
        doc.build(story, canvasmaker=NumberedCanvas)
        return output_path