import json
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from fastapi import APIRouter, Depends, HTTPException, Header
from pydantic import BaseModel
from typing import Optional
import httpx
from sqlalchemy.orm import Session
from ..database.database import get_db
from ..database.models import Review

router = APIRouter(prefix="/notify", tags=["Notifications"])

def get_user(x_user_id: Optional[str] = Header(None, alias="X-User-ID")):
    if not x_user_id:
        raise HTTPException(status_code=401, detail="X-User-ID header is required.")
    return x_user_id

class WebhookRequest(BaseModel):
    review_id: str
    webhook_url: str

class EmailRequest(BaseModel):
    review_id: str
    email: str

def build_summary_html(data: dict) -> str:
    scores = data.get("scores", {})
    pred = data.get("predictions", {})
    findings = data.get("findings", [])
    target = data.get("target_name", "Unknown")
    review_id = data.get("review_id", "N/A")
    overall = scores.get("overall", 0)
    risk = pred.get("risk_level", "N/A")
    crit = sum(1 for f in findings if f.get("severity") == "CRITICAL")
    high = sum(1 for f in findings if f.get("severity") == "HIGH")
    improved_code = data.get("improved_code", "")
    code_improvements = data.get("code_improvements", [])

    improved_html = ""
    if improved_code:
        imps_list = "".join([f"<li style='margin-bottom:4px'>{imp}</li>" for imp in code_improvements[:4]])
        safe_snippet = (
            improved_code[:600]
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\n", "<br/>")
            .replace(" ", "&nbsp;")
        )
        improved_html = f"""
        <div style="margin-top:20px;padding:14px;background:#0d1117;border:1px solid #30363d;border-radius:8px">
          <h3 style="color:#10b981;font-size:15px;margin:0 0 8px 0">&#10004; Recommended Improved Code</h3>
          {f'<ul style="color:#86efac;font-size:12px;margin:0 0 10px 0;padding-left:18px">{imps_list}</ul>' if imps_list else ''}
          <div style="font-family:monospace;font-size:11px;color:#e6edf3;background:#161b22;padding:10px;border-radius:6px;overflow-x:auto;line-height:1.4">
            {safe_snippet}
          </div>
        </div>
        """

    return f"""
<html><body style="font-family:Arial,sans-serif;background:#0b0f19;color:#e2e8f0;padding:24px">
  <div style="max-width:600px;margin:0 auto;background:#111827;border-radius:12px;padding:24px;border:1px solid #1e293b">
    <h1 style="color:#3b82f6;font-size:22px">Smart AI Code Reviewer Report</h1>
    <p style="color:#94a3b8">Review ID: {review_id} &bull; Target: {target}</p>
    <table style="width:100%;border-collapse:collapse;margin:16px 0">
      <tr><td style="padding:8px;color:#94a3b8">Overall Score</td><td style="padding:8px;font-weight:700;color:{'#34d399' if overall >= 80 else '#f59e0b'}">{overall}/100</td></tr>
      <tr><td style="padding:8px;color:#94a3b8">Risk Level</td><td style="padding:8px;font-weight:700;color:#ef4444">{risk}</td></tr>
      <tr><td style="padding:8px;color:#94a3b8">Critical Issues</td><td style="padding:8px;font-weight:700;color:#fca5a5">{crit}</td></tr>
      <tr><td style="padding:8px;color:#94a3b8">High Issues</td><td style="padding:8px;font-weight:700;color:#f87171">{high}</td></tr>
      <tr><td style="padding:8px;color:#94a3b8">Security Score</td><td style="padding:8px;color:#93c5fd">{scores.get('security', 0)}/100</td></tr>
      <tr><td style="padding:8px;color:#94a3b8">Quality Score</td><td style="padding:8px;color:#93c5fd">{scores.get('code_quality', 0)}/100</td></tr>
      <tr><td style="padding:8px;color:#94a3b8">Performance Score</td><td style="padding:8px;color:#93c5fd">{scores.get('performance', 0)}/100</td></tr>
    </table>
    {improved_html}
    <p style="font-size:12px;color:#475569;margin-top:20px">Generated by Smart Multi-Agent AI Code Reviewer v2.0.0</p>
  </div>
</body></html>"""

@router.post("/webhook")
async def dispatch_webhook(req: WebhookRequest, user_id: str = Depends(get_user), db: Session = Depends(get_db)):
    review = db.query(Review).filter(Review.id == req.review_id, Review.user_id == user_id).first()
    if not review:
        raise HTTPException(status_code=404, detail="Review not found.")
    data = json.loads(review.review_data) if review.review_data else {}
    scores = data.get("scores", {})
    pred = data.get("predictions", {})
    payload = {
        "review_id": req.review_id,
        "target": data.get("target_name", ""),
        "language": data.get("primary_language", ""),
        "overall_score": scores.get("overall", 0),
        "risk_level": pred.get("risk_level", "N/A"),
        "risk_score": pred.get("overall_risk", 0),
        "critical_findings": sum(1 for f in data.get("findings", []) if f.get("severity") == "CRITICAL"),
        "high_findings": sum(1 for f in data.get("findings", []) if f.get("severity") == "HIGH"),
        "source": "Smart AI Code Reviewer v2.0.0"
    }
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            response = await client.post(req.webhook_url, json=payload)
        return {"status": "success", "http_status": response.status_code, "payload_sent": payload}
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Webhook delivery failed: {str(e)}")

@router.post("/email/preview")
def email_preview(req: EmailRequest, user_id: str = Depends(get_user), db: Session = Depends(get_db)):
    review = db.query(Review).filter(Review.id == req.review_id, Review.user_id == user_id).first()
    if not review:
        raise HTTPException(status_code=404, detail="Review not found.")
    data = json.loads(review.review_data) if review.review_data else {}
    html = build_summary_html(data)
    smtp_host = os.getenv("SMTP_HOST", "")
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")
    email_sent = False
    if smtp_host and smtp_user and smtp_pass:
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = f"[AI Code Review] {data.get('target_name','Code')} - Score {data.get('scores',{}).get('overall',0)}/100"
            msg["From"] = smtp_user
            msg["To"] = req.email
            msg.attach(MIMEText(html, "html"))
            with smtplib.SMTP_SSL(smtp_host, 465) as server:
                server.login(smtp_user, smtp_pass)
                server.sendmail(smtp_user, req.email, msg.as_string())
            email_sent = True
        except Exception:
            email_sent = False
    return {"status": "success", "email_sent": email_sent, "preview_html": html, "recipient": req.email}